config/routes.rb
Rails.application.routes.draw do
  resources :homes
  root "homes#index"
  resources :transactions do 
    collection do
      post :response_handler
    end
  end
  post "/transaction/ccavRequestHandler", to: "transactions#create"
  post "/transaction/ccavResponseHandler", to: "transactions#response1"
  post "/transaction/ccavResponseHandlerCancel", to: "transactions#response_cancel"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[ show edit update destroy ]
  include ApplicationHelper


  # GET /homes or /homes.json
  def index
    @homes = Home.all
    # data = {
    #     order_id: 'order-id-1',
    #     currency: 'INR',
    #     amount: '100',
    #     redirect_url: "#{ENV["REDIRECT_URL"]}/transaction/ccavResponseHandler",
    #     cancel_url: "#{ENV["REDIRECT_URL"]}/transaction/ccavResponseHandlerCancel"

    # }

    # # enc_request=63957FB55DD6E7B968A7588763E08B240878046EF2F520C44BBC63FB9CCE726209A4734877F5904445591304ABB2F5E598B951E39EAFB9A24584B00590ADB077ADE5E8C444EAC5A250B1EA96F68D22E44EA2515401C2CD753DBA91BD0E7DFE7341BE1E7B7550&access_code=AVWP23KB52BT68PWTB&command=confirmOrder&request_type=JSON&response_type=JSON&version=1.1

    # @encRequest = CcavenuePayment.encrypted_data(data)
    
    # @ccavenue_request_url = CcavenuePayment.request_url
    # @ccavenue_access_code = ENV.fetch('CCAVENUE_ACCESS_CODE').freeze
    # @CCAVENUE_MERCHANT_ID = ENV.fetch('CCAVENUE_MERCHANT_ID').freeze

  end

  def payment_confirm
    # parameter to response is encrypted reponse we get from CCavenue
    @data = 'null'
    if params['encResponse'].present?
      @data = CcavenuePayment.decrypted_data(params['encResponse']) 
      # Return parameters:
      #   Auth Description: <String: Payment Failed/Success>
      #   Checksum Verification <Bool: True/False>
      #   Response Data: <HASH/Array: Order_id, amount etc>
    end
  end

  # GET /homes/1 or /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to home_url(@home), notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to home_url(@home), notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url, notice: "Home was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.require(:home).permit(:title)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	skip_before_action :verify_authenticity_token

	def new
	end

	def create
	end

	def response_handler
	end

	def response1
		@data = CcavenuePayment.decrypted_data(params['encResp'])
		@json_data = {}
		@data.split("&").each do |str|
			str_array = str.split("=")
			@json_data[str_array[0]] = str_array[1] 
		end
		# ActionCable.server.broadcast "messages", {:message=>@json_data}
		# Crypto.new.decrypt(params["encResp"], ENV["CCAVENUE_WORKING_KEY"])
	end

	def response_cancel
		@data = CcavenuePayment.decrypted_data(params['encResp'])
		@json_data = {}
		@data.split("&").each do |str|
			str_array = str.split("=")
			@json_data[str_array[0]] = str_array[1] 
		end
	end
end


# def response1
# 		@data = CcavenuePayment.decrypted_data(params['encResp'])
# 		json_data = {}
# 		@data.split("&").each do |str|
# 			str_array = str.split("=")
# 			json_data[str_array[0]] = str_array[1] 
# 		end
# 		puts json_data
# 		head :ok
# 	end

app/helpers/application_helper.rb
module ApplicationHelper

	def verifyChecksum( merchantID,  orderID,  amount,  authDesc,  workingKey,  checksum) 
    String str = merchantID+”|”+orderID+”|”+amount+”|”+authDesc+”|”+workingKey
    String newChecksum = Zlib::adler32(str).to_s
    return (newChecksum.eql?(checksum)) ? true : false
  end

  def getChecksum( merchantID,  orderID,  amount,  redirectUrl,  workingKey)
    String str = merchantID + "|" + orderID + "|" + amount + "|" + redirectUrl + "|" + workingKey;
    return Zlib::adler32(str)
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
        <% home.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
welcome

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @home.title %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CcAvenue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/create.html.erb
<html>
<head>
<title> Non-Seamless-kit</title>
</head>
<body>
<center>
<%
  merchantData=""
  working_key=ENV["CCAVENUE_WORKING_KEY"]    #Put in the 32 Bit Working Key provided by CCAVENUES.  
  access_code=ENV["CCAVENUE_ACCESS_CODE"]    #Put in the Access Code in quotes provided by CCAVENUES.
  
  params.each do |key,value|
      merchantData += key+"="+value+"&" 
  end
  
  crypto = Crypto.new
  encrypted_data = crypto.encrypt(merchantData,working_key)
  puts "*********************************#{encrypted_data}"
%>
  <form method="post" name="redirect" action="<%= ENV["PAYMENT_URL"] %>"> 
    <input type="hidden" name="encRequest" value="<%=encrypted_data%>" />
    <input type="hidden" name="access_code" value="<%=access_code%>" />
  </form>
</center>
<script language="javascript">document.redirect.submit();</script>
</body>
</html>

app/views/transactions/new.html.erb
<html>
<head>
</head>
<body>
	<form method="POST" name="customerData" id="myform" action="/transaction/ccavRequestHandler" style="display: none;">
		<table width="40%" height="1" border='1' align="center"><caption><font size="4" color="blue"><b>Integration Kit</b></font></caption></table>
			<table width="40%" height="100" border='1' align="center">
				<tr>
					<td>Parameter Name:</td><td>Parameter Value:</td>
				</tr>
				<tr>
					<td colspan="2"> Compulsory information</td>
				</tr>
				<tr>
					<td>Merchant Id	:</td><td><input type="text" name="merchant_id" value="<%= ENV["CCAVENUE_MERCHANT_ID"] %>"/></td>
				</tr>
				<tr>
					<td>Order Id	:</td><td><input type="text" name="order_id" value="123654789"/></td>
				</tr>
				<tr>
					<td>Amount	:</td><td><input type="text" name="amount" value="1.00"/></td>
				</tr>
				<tr>
					<td>Currency	:</td><td><input type="text" name="currency" value="INR"/></td>
				</tr>
				<tr>
					<td>Redirect URL	:</td><td><input type="text" name="redirect_url" value="<%= ENV["REDIRECT_URL"] %>/transaction/ccavResponseHandler"/></td>
				</tr>
			 	<tr>
			 		<td>Cancel URL	:</td><td><input type="text" name="cancel_url" value="<%= ENV["REDIRECT_URL"] %>/transaction/ccavResponseHandlerCancel"/></td>
			 	</tr>
			 	<tr>
					<td>Language	:</td><td><input type="text" name="language" value="EN"/></td>
				</tr>
		     	<tr>
		     		<td colspan="2">Billing information(optional):</td>
		     	</tr>
		        <tr>
		        	<td>Billing Name	:</td><td><input type="text" name="billing_name" value="Charli"/></td>
		        </tr>
		        <tr>
		        	<td>Billing Address	:</td><td><input type="text" name="billing_address" value="Room no 1101, near Railway station Ambad"/></td>
		        </tr>
		        <tr>
		        	<td>Billing City	:</td><td><input type="text" name="billing_city" value="Indore"/></td>
		        </tr>
		        <tr>
		        	<td>Billing State	:</td><td><input type="text" name="billing_state" value="MP"/></td>
		        </tr>
		        <tr>
		        	<td>Billing Zip	:</td><td><input type="text" name="billing_zip" value="425001"/></td>
		        </tr>
		        <tr>
		        	<td>Billing Country	:</td><td><input type="text" name="billing_country" value="India"/></td>
		        </tr>
		        <tr>
		        	<td>Billing Tel	:</td><td><input type="text" name="billing_tel" value="9876543210"/></td>
		        </tr>
		        <tr>
		        	<td>Billing Email	:</td><td><input type="text" name="billing_email" value="person@gmail.com"/></td>
		        </tr>
		        <tr>
		        	<td colspan="2">Shipping information(optional)</td>
		        </tr>
		        <tr>
		        	<td>Shipping Name	:</td><td><input type="text" name="delivery_name" value="Chaplin"/></td>
		        </tr>
		        <tr>
		        	<td>Shipping Address	:</td><td><input type="text" name="delivery_address" value="room no.701 near bus stand"/></td>
		        </tr>
		        <tr>
		        	<td>shipping City	:</td><td><input type="text" name="delivery_city" value="Hyderabad"/></td>
		        </tr>
		        <tr>
		        	<td>shipping State	:</td><td><input type="text" name="delivery_state" value="Andhra"/></td>
		        </tr>
		        <tr>
		        	<td>shipping Zip	:</td><td><input type="text" name="delivery_zip" value="425001"/></td>
		        </tr>
		        <tr>
		        	<td>shipping Country	:</td><td><input type="text" name="delivery_country" value="India"/></td>
		        </tr>
		        <tr>
		        	<td>Shipping Tel	:</td><td><input type="text" name="delivery_tel" value="9595226054"/></td>
		        </tr>
		        <tr>
		        	<td>Merchant Param1	:</td><td><input type="text" name="merchant_param1" value="additional Info."/></td>
		        </tr>
		        <tr>
		        	<td>Merchant Param2	:</td><td><input type="text" name="merchant_param2" value="additional Info."/></td>
		        </tr>
				<tr>
					<td>Merchant Param3	:</td><td><input type="text" name="merchant_param3" value="additional Info."/></td>
				</tr>
				<tr>
					<td>Merchant Param4	:</td><td><input type="text" name="merchant_param4" value="additional Info."/></td>
				</tr>
				<tr>
					<td>Merchant Param5	:</td><td><input type="text" name="merchant_param5" value="additional Info."/></td>
				</tr>
				<tr>
					<td>Promo Code	:</td><td><input type="text" name="promo_code" value=""/></td>
				</tr>
				<tr>
					<td>Vault Info.	:</td><td><input type="text" name="customer_identifier" value=""/></td>
				</tr>
		 		<tr>
		        	<td>Integration Type	:</td><td><input type="text" name="integration_type" value="iframe_normal"/></td>
		        </tr>
		        <tr>
		        	<td></td><td><INPUT TYPE="submit" value="CheckOut"></td>
		        </tr>
	      	</table>
	      </form>


	      <div class="container">
        <br/><br/>
        <h3 class="h3"></h3>
        <h3 class="h3"></h3>
        <div class="row">
            <div class="col-md-12">
                <div class="loader14">
                    <div class="loader-inner">
                        <div class="box-1"></div>
                        <div class="box-2"></div>
                        <div class="box-3"></div>
                        <div class="box-4"></div>
                    </div>
                    <!-- <span class="text">Please Wait</span> -->
                </div>
            </div>
        </div>
        <br/><br/>
    </div>


</body>
</html>
<script type="text/javascript">
	$(document).ready(function(){
		setTimeout(function() {
        // $("#myform").trigger('submit.rails');
		 	$("form").submit();
     }, 1000);
	});
</script>

app/views/transactions/response1.html.erb
<%= @json_data rescue nil %>
<script type="text/javascript">
	// window.postMessage("Response Success");
	window.ReactNativeWebView.postMessage("<%= @json_data["order_status"].to_s %>");
	// window.ReactNativeWebView.postMessage("Success");
</script>

app/views/transactions/response_cancel.html.erb
<%= @json_data rescue nil %>
<script type="text/javascript">
	// window.postMessage("Response Success");
	// window.ReactNativeWebView.postMessage("Failed");
	window.ReactNativeWebView.postMessage("<%= @json_data["order_status"].to_s %>");
</script>

app/views/transactions/response_handler.html.erb
<html>
<head>  
  <title>Response Handler</title>
  <%= csrf_meta_tags%>
</head>
<body>
<%  
  workingKey=ENV["CCAVENUE_WORKING_KEY"]  #Put in the 32 Bit Working Key provided by CCAVENUES.   
  encResponse=params[:encResp]
  crypto = Crypto.new 
  decResp=crypto.decrypt(encResponse,workingKey);
  decResp = decResp.split("&")
%>
<center>
    <font size="4" color="blue"><b>Response Page</b></font>
    <table border="1">
<tr>
  <td><b>Parameter Name</b></td>
  <td><b>Parameter Value</b></td>

  <%decResp.each do |key|%> 
    <tr>
      <td><%=key.from(0).to(key.index("=")-1)%> </td>
      <td><%=key.from(key.index("=")+1).to(-1)%> </td>
    </tr>
  <%end%>
</table>
</center>
</body>
</html>